import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/functions";
import { Toaster } from "@/components/ui/sonner";
import type { Viewport } from "next";
import AuthProvider from "@/lib/providers/AuthProvider";
import { Background } from "@/components/ui/background";
import SWRProvider from "@/lib/providers/SwrProvider";

const maprope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  colorScheme: "dark",
  themeColor: "black",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <SWRProvider>
          <Toaster />
          <body className={cn(maprope.className, "antialiased")}>
              {children}
          </body>
        </SWRProvider>
      </AuthProvider>
    </html>
  );
}
